pelicula('Deadpool', 'Deadpool es una película de superhéroes de 2016, protagonizada por Ryan Reynolds como Wade Wilson / Deadpool. Tras un experimento, Wade adquiere 
habilidades mutantes y busca venganza. La película tiene una duración de 108 minutos y está disponible en inglés y español').

pelicula('Mad_Max:Fury_Road', 'Mad Max: Fury Road es una película de acción y ciencia ficción de 2015, dirigida por George Miller. Está protagonizada por Tom Hardy como Max Rockatansky y Charlize Theron como Imperator Furiosa. La película sigue a Max y Furiosa en su intento de escapar de un tirano en un mundo post-apocalíptico. Tiene una duración de 120 minutos y está disponible en inglés.').

pelicula('The_Dark_Knight', 'The Dark Knight es una película de superhéroes de 2008, protagonizada por Christian Bale como Batman y Heath Ledger como el Joker. La película sigue a Batman mientras lucha contra el crimen organizado en Ciudad Gótica. Tiene una duración de 152 minutos y está disponible en inglés').

pelicula('The_Matrix', 'The Matrix es una película de ciencia ficción de 1999, dirigida por los hermanos Wachowski. Está protagonizada por Keanu Reeves como Neo, Laurence Fishburne como Morpheus y Carrie-Anne Moss como Trinity. La película sigue a Neo mientras descubre la verdad sobre la realidad simulada en la que vive y se une a la resistencia contra las máquinas. Tiene una duración de 136 minutos y está disponible en inglés.').

pelicula('Avengers_Endgame', 'Avengers: Endgame es una película de superhéroes de 2019, dirigida por Anthony y Joe Russo. Está protagonizada por un elenco extenso que incluye a Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson y muchos más. La película sigue a los Vengadores mientras intentan revertir los efectos devastadores del chasquido de Thanos y restaurar la paz en el universo. Tiene una duración de 181 minutos y está disponible en inglés y español.').

pelicula('Supercool', 'Supercool es una película de comedia adolescente de 2007 dirigida por Greg Mottola. Está protagonizada por Jonah Hill y Michael Cera como dos amigos de secundaria que se embarcan en una loca aventura para obtener alcohol para una fiesta. La película sigue sus desventuras y explora temas de amistad y crecimiento. Supercool tiene una duración de 113 minutos y está disponible en inglés y español.').

pelicula('A_la_mierda_con_los_zombies', 'A la mierda con los zombies es una película de terror y comedia del año 2015, dirigida por Christopher Landon. Está protagonizada por Tye Sheridan, Joey Morgan y Logan Miller. La trama sigue a un grupo de amigos que se ven envueltos en un apocalipsis zombie durante una fiesta de pijamas. La película combina humor y terror mientras los personajes luchan por sobrevivir a la invasión de los muertos vivientes. Tiene una duración de 1 hora y 33 minutos y está disponible en inglés y español.').

pelicula('Son_como_ninos', 'Son como niños es una película de comedia de 2010 dirigida por Dennis Dugan. Está protagonizada por Adam Sandler, Kevin James, Chris Rock, David Spade y Rob Schneider. La trama sigue a un grupo de amigos de la infancia que se reúnen después de muchos años para recordar viejos tiempos en un fin de semana junto a sus familias en un lago. La película combina humor y nostalgia mientras los personajes lidian con situaciones cómicas y caóticas. Tiene una duración de 102 minutos y está disponible en inglés y español.').

pelicula('Ted', 'Ted es una comedia de 2012 dirigida por Seth MacFarlane. Está protagonizada por Mark Wahlberg, Mila Kunis y Seth MacFarlane como la voz de Ted, el oso de peluche viviente. La trama sigue a John Bennett, quien, como niño, deseó que su oso de peluche Ted cobrara vida, y años después, Ted sigue siendo su mejor amigo, pero esto comienza a complicar su relación con su novia. La película combina humor irreverente con momentos de ternura y reflexión sobre la amistad. Tiene una duración de 106 minutos y está disponible en inglés.').

pelicula('Zombieland', 'Zombieland es una comedia de terror de 2009 dirigida por Ruben Fleischer. Está protagonizada por Jesse Eisenberg, Woody Harrelson, Emma Stone y Abigail Breslin. La trama sigue a un grupo de supervivientes mientras navegan por un mundo post-apocalíptico lleno de zombis. Cada uno tiene su propia regla de supervivencia, y juntos intentan encontrar un refugio seguro. La película combina humor negro con acción y elementos de terror de una manera única. Tiene una duración de 88 minutos y está disponible en inglés y español.').

pelicula('Annabelle', 'Annabelle es una película de terror de 2014 dirigida por John R. Leonetti. Es un spin-off de la exitosa película "El Conjuro". La trama sigue a una joven pareja que recibe como regalo una muñeca antigua llamada Annabelle, que desencadena una serie de eventos terroríficos en su hogar. La película explora la historia detrás de la muñeca poseída y los intentos de la pareja por detener el mal que han desatado. Annabelle combina suspense, sustos y una atmósfera inquietante. Tiene una duración de 99 minutos y está disponible en inglés.').

pelicula('El_Conjuro', 'El Conjuro es una película de terror de 2013 dirigida por James Wan. Está basada en las experiencias reales de los investigadores paranormales Ed y Lorraine Warren. La trama sigue a la familia Perron, que comienza a experimentar fenómenos paranormales después de mudarse a una casa rural en Rhode Island. Los Warren son llamados para investigar y se enfrentan a una entidad malévola que amenaza la vida de la familia. La película combina una narrativa escalofriante con una atmósfera tensa y momentos de terror genuino. Tiene una duración de 112 minutos y está disponible en inglés.').

pelicula('El_cadaver_de_la_novia', 'El cadáver de la novia es una película de animación stop-motion de 2005 dirigida por Tim Burton y Mike Johnson. Está basada en un poema homónimo de Tim Burton. La trama sigue a Victor, un joven que accidentalmente se casa con el cadáver de una novia llamada Emily mientras practicaba sus votos de matrimonio en el bosque. Victor se encuentra en un triángulo amoroso entre Emily y su prometida viva, Victoria. La película combina elementos góticos con humor oscuro y presenta una estética visualmente impresionante. Tiene una duración de 77 minutos y está disponible en inglés.').

pelicula('Martyrs', 'Martyrs es una película francesa de terror y suspenso de 2008, dirigida por Pascal Laugier. La trama sigue a Lucie, una joven que fue torturada y abusada cuando era niña, y Anna, su amiga que la ayuda a vengarse de sus captores. Sin embargo, su búsqueda de venganza las lleva a un territorio oscuro y perturbador. La película es conocida por su intensidad y su enfoque en temas como el sufrimiento humano y la búsqueda de la verdad. Martyrs es una experiencia visceral que desafía las convenciones del género de terror. Tiene una duración de 99 minutos y está disponible en francés con subtítulos en español.').

pelicula('Archivo_253', 'Archivo 253 es una película mexicana de terror de 2015, dirigida por Abe Rosenberg. La trama sigue a un grupo de personas que deciden pasar la noche en un antiguo hospital psiquiátrico abandonado, conocido por sus historias de actividad paranormal. Armados con cámaras, intentan documentar los fenómenos inexplicables que ocurren en el lugar. Sin embargo, pronto descubren que no están solos y que algo siniestro los acecha en las sombras. La película ofrece una atmósfera inquietante y momentos de suspenso mientras explora los límites entre lo real y lo sobrenatural. Tiene una duración de 79 minutos y está disponible en español.').

